### ISSUE TITLE
[QuickStart] ‘/project/kodokojo.jar’: not found

### ISSUE THREAD

**Issue by ctranxuan** [kodokojo/kodokojo#28]
Hi,
When running the `docker-compose`  command:

`docker-compose -f src/test/resources/docker/full/docker-compose.yml up -d`

<details>
`docker-compose -f src/test/resources/docker/full/docker-compose.yml up -d`

<pre><code>Creating full_haproxy_1...
full_zookeeper_1 is up-to-date
full_redis_1 is up-to-date
Creating full_mesos-slave_1...
full_mesos-master_1 is up-to-date
Creating full_kodokojo_1...
Container command 'java -Dlogback.configurationFile=/debug-logback.xml -Djavax.net.ssl.keyStore=/keystore.jks -Djavax.net.ssl.keyStorePassword=password -Dsecurity.ssl.rootCa.ks.alias=rootcafake -Dsecurity.ssl.rootCa.ks.password=password -Dapplication.dns.domain=kodokojo.dev -Dmarathon.url=http://192.168.99.100:8080 -Dmarathon.ignore.constraint=TRUE -Dlb.host=192.168.99.100 -jar /project/kodokojo.jar' not found or does not exist.
</code></pre>
</details>

I've got ` -jar /project/kodokojo.jar' not found or does not exist`. 
The image kodokojo/kodokojo seems to be well built so:

<details>
`docker inspect kodokojo/kodokojo`
<pre><code class="json">
[
    {
        "Id": "sha256:3da8b5f5bd0e37a9be6b5722eaa2859dac2dd1972c587cf57a2acf5013fc4c56",
        "RepoTags": [
            "kodokojo/kodokojo:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:3129388d0844481e4749399a2745a09dd681d2e46a469ebc83490a05d029823f",
        "Comment": "",
        "Created": "2016-07-17T17:49:09.65008542Z",
        "Container": "3c78549dc70d2e20ee7220321fb87634b6486ac5034d386a4912ec077ec37d02",
        "ContainerConfig": {
            "Hostname": "6250540837a8",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre",
                "JAVA_VERSION=8u91",
                "JAVA_DEBIAN_VERSION=8u91-b14-1~bpo8+1",
                "CA_CERTIFICATES_JAVA_VERSION=20140324"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ENTRYPOINT [\"java\" \"-jar\" \"/project/kodokojo.jar\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:3129388d0844481e4749399a2745a09dd681d2e46a469ebc83490a05d029823f",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "java",
                "-jar",
                "/project/kodokojo.jar"
            ],
            "OnBuild": [],
            "Labels": {
                "kodokojo-componentType": "project-manager"
            }
        },
        "DockerVersion": "1.11.2",
        "Author": "",
        "Config": {
            "Hostname": "6250540837a8",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre",
                "JAVA_VERSION=8u91",
                "JAVA_DEBIAN_VERSION=8u91-b14-1~bpo8+1",
                "CA_CERTIFICATES_JAVA_VERSION=20140324"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "sha256:3129388d0844481e4749399a2745a09dd681d2e46a469ebc83490a05d029823f",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "java",
                "-jar",
                "/project/kodokojo.jar"
            ],
            "OnBuild": [],
            "Labels": {
                "kodokojo-componentType": "project-manager"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 352422491,
        "VirtualSize": 352422491,
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:42755cf4ee95900a105b4e33452e787026ecdefffcc1992f961aa286dc3f7f95",
                "sha256:d1c800db26c75f0aa5881a5965bd6b6abf5101dbb626a4be5cb977cc8464de3b",
                "sha256:79aea7ff834ff37b131ead8c6a5d5cf0ec54d9aed35743e57815ab7540e64cb5",
                "sha256:788c89434030a7b00ee299cd14f9f39a35937714b6375743bcb760133772ea17",
                "sha256:9176ec7d1a0ca5b937b18be1002de358b12932d1ce58a468da7e7c546275a5b9",
                "sha256:a703d1f77f179885cb10b6f6778887cc7529b32cdf66e6adba5b92d0616141fe",
                "sha256:b5d7c200f6f3d21161fda8ad0990b35fb8d90f8b763bc392f5dfbb35cd2cf13b",
                "sha256:4ab4f038342fbce2aaa22999abf2a7ace47ddd545e6995bfad3177b10ef59436"
            ]
        }
    }
]
</code></pre>
</details>

But I have no clue how to fix that.
Thanks in advance!

My environment is:
- Docker version 1.11.1, build 5604cbe
- Ubuntu 15.10

**Comment by jpthiery** [comment]
Hi,
if kodokojo.jar isn't present in Dokcer image, i thing that build had failed.
I test your PR #27 and i will have a look on this issue.

**Comment by ctranxuan** [comment]
I've started the image in standalone, the jar seems to be present. Although it started with a stacktrace related to AWS.
I can provide it, if you wish.

**Comment by jpthiery** [comment]
If you run Kodo Kojo over AWS, you need to give access to Kodo Kojo to Route53 and SES.
We may Open source ours Terraform and Ansible playbook as soon as possible.

Your stack trace may be relative to those access.

**Comment by ctranxuan** [comment]
Sorry for the wrong information. Actually, it's not an AWS issue.
Below the stacktrace. I guess the standalone image needs to be run with some params.

<details>
18:18:48.923 [main] INFO  io.kodokojo.Launcher - Starting Kodo Kojo.
18:18:53.619 [main] WARN  io.kodokojo.config.module.AwsModule - Unable to retrieve AWS credentials.
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalArgumentException: baseDomainName must be defined.
  at io.kodokojo.config.module.ServiceModule.provideBrickUrlFactory(ServiceModule.java:93)
  at io.kodokojo.config.module.ServiceModule.provideBrickUrlFactory(ServiceModule.java:93)
  while locating io.kodokojo.brick.BrickUrlFactory
    for parameter 0 at io.kodokojo.config.module.ServiceModule.provideBrickConfigurerProvider(ServiceModule.java:72)
  at io.kodokojo.config.module.ServiceModule.provideBrickConfigurerProvider(ServiceModule.java:72)
  at io.kodokojo.config.module.ServiceModule.provideBrickConfigurerProvider(ServiceModule.java:72)
  while locating io.kodokojo.brick.BrickConfigurerProvider
    for parameter 1 at io.kodokojo.config.module.MarathonModule.provideBrickManager(MarathonModule.java:50)
  at io.kodokojo.config.module.MarathonModule.provideBrickManager(MarathonModule.java:50)
  at io.kodokojo.config.module.MarathonModule.provideBrickManager(MarathonModule.java:50)
  while locating io.kodokojo.service.BrickManager
    for parameter 1 at io.kodokojo.config.module.ActorModule.provideBrickConfigurationStarterActor(ActorModule.java:51)
  at io.kodokojo.config.module.ActorModule.provideBrickConfigurationStarterActor(ActorModule.java:51)
  while locating akka.actor.ActorRef annotated with @com.google.inject.name.Named(value=brickConfigurationStarter)
    for parameter 0 at io.kodokojo.config.module.ActorModule.provideBrickConfigurationStarter(ActorModule.java:63)
  at io.kodokojo.config.module.ActorModule.provideBrickConfigurationStarter(ActorModule.java:63)
  at io.kodokojo.config.module.ActorModule.provideBrickConfigurationStarter(ActorModule.java:63)
  while locating io.kodokojo.brick.BrickConfigurationStarter
    for parameter 1 at io.kodokojo.config.module.ServiceModule.provideProjectManager(ServiceModule.java:87)
  at io.kodokojo.config.module.ServiceModule.provideProjectManager(ServiceModule.java:87)
  at io.kodokojo.config.module.ServiceModule.provideProjectManager(ServiceModule.java:87)
  while locating io.kodokojo.service.ProjectManager
    for parameter 3 at io.kodokojo.endpoint.ProjectSparkEndpoint.<init>(ProjectSparkEndpoint.java:60)
  while locating io.kodokojo.endpoint.ProjectSparkEndpoint
  while locating io.kodokojo.endpoint.SparkEndpoint annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=4, type=MULTIBINDER, keyType=)
  at io.kodokojo.config.module.endpoint.UserEndpointModule.configure(UserEndpointModule.java:29) (via modules: io.kodokojo.config.module.endpoint.UserEndpointModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<io.kodokojo.endpoint.SparkEndpoint>
    for parameter 3 at io.kodokojo.config.module.RestEndpointModule.provideRestEntrypoint(RestEndpointModule.java:41)
  at io.kodokojo.config.module.RestEndpointModule.provideRestEntrypoint(RestEndpointModule.java:41)
  at io.kodokojo.config.module.RestEndpointModule.provideRestEntrypoint(RestEndpointModule.java:41)
  while locating io.kodokojo.endpoint.HttpEndpoint

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at io.kodokojo.Launcher.main(Launcher.java:68)
Caused by: java.lang.IllegalArgumentException: baseDomainName must be defined.
	at io.kodokojo.brick.DefaultBrickUrlFactory.<init>(DefaultBrickUrlFactory.java:34)
	at io.kodokojo.config.module.ServiceModule.provideBrickUrlFactory(ServiceModule.java:93)
	at io.kodokojo.config.module.ServiceModule$$FastClassByGuice$$8e67de7d.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:272)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:167)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:167)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:167)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:167)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:167)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:375)
	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:258)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:167)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 2 more
</details>

**Comment by jpthiery** [comment]
You are right.
In this case, you need to provide the following properties : `application.dns.domain`.

I may complet our documentation about Kodo Kojo properties and configuration soon.

You could have a look on the docker-compose.yml file to get minimalist properties.

**Comment by ctranxuan** [comment]
Does it mean that I need to change the `src/main/docker/local/Dockerfile` to handle these properties?
Never mind, I will have a look and try.
Cheers.

**Comment by jpthiery** [comment]
Nop,
this properties depends of your running context, it must be defined at runtime with environment properties or file properties or java argument properties.
