### ISSUE TITLE
Cannot install NodeJS on Jenkins 2.19.2

### ISSUE THREAD

**Issue by jsmadja** [kodokojo/kodokojo#72]
How to reproduce :

1. Create a new kodokojo account
2. Update Jenkins to the newer version
3. Install *NodeJS Plugin* v0.2.1
4. Configure the plugin in *Global Tool Configuration* section
5. Create a NodeJS installation (Install automatically from nodejs.org) with version *6.9.1*
6. Create a new job (Freestyle project)
7. Add a build step of type : *Execute NodeJS script*
8. In script textfield type *npm install && npm test*

See my errors below :

Building in workspace /var/jenkins_home/jobs/fightcade/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://gitlab-fightcade.kodokojo.io/julien.smadja/fightcade.git # timeout=10
Fetching upstream changes from https://gitlab-fightcade.kodokojo.io/julien.smadja/fightcade.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://gitlab-fightcade.kodokojo.io/julien.smadja/fightcade.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision a8acbdece327317e8b8e7692c89590e9850c5d99 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a8acbdece327317e8b8e7692c89590e9850c5d99
 > git rev-list a8acbdece327317e8b8e7692c89590e9850c5d99 # timeout=10
[workspace] $ /bin/sh -xe /tmp/hudson1742166873105982264.sh
Unpacking https://nodejs.org/dist/v6.9.1/node-v6.9.1-linux-x64.tar.gz to /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs on Jenkins
[workspace] $ /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/bin/node /tmp/hudson8240189796332388349.js
FATAL: command execution failed
java.io.IOException: Cannot run program "/var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/bin/node" (in directory "/var/jenkins_home/jobs/fightcade/workspace"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:243)
	at hudson.Proc$LocalProc.<init>(Proc.java:212)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:815)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$ProcStarter.join(Launcher.java:388)
	at jenkins.plugins.nodejs.NodeJsCommandInterpreter.perform(NodeJsCommandInterpreter.java:84)
	at jenkins.plugins.nodejs.NodeJsCommandInterpreter.perform(NodeJsCommandInterpreter.java:42)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 16 more
Build step 'Execute NodeJS script' marked build as failure
Finished: FAILURE

**Comment by jpthiery** [comment]
Kodo Kojo provide a Jenkins instance which use alpine linux. This pluging seems to meet some trouble when trying to install Node.
